name: Deploy Kube-Prometheus-Stack to EKS

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up AWS CLI and authenticate
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Step 3: Install kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0' # Specify the kubectl version you need

    # Step 4: Install Helm
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        helm-version: 'v3.x' # Specify the Helm version

    # Step 5:  Add bitnami
    - name: Add Bitnami Helm repo and update
      run: |
          helm init
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

    # Step 6: Configure kubeconfig for EKS
    - name: Set up kubeconfig
      run: |
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    # Step 7: Deploy kube-prometheus-stack using Helm
    - name: Deploy kube-prometheus-stack
      run: |
        helm init
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
          --namespace monitoring --create-namespace \

    # Step 8: Verify the deployment (Optional)
    - name: Verify Deployment
      run: |
        kubectl get pods -n monitoring
        kubectl get svc -n monitoring
